### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cngJo** [jop-software/redmine-development#1]
Create documentation about the following points

- [ ] General project idea and structure 
- [ ] First Startup
- [ ] Start a new Plugin
- [ ] Start a new Theme
