### ISSUE TITLE
Initial set of helper scripts

### ISSUE THREAD

**Issue by cngJo** [jop-software/redmine-development#2]
We should create some helper-script to abstract some common tasks
- [x] Start / Stop
- [x] Create a new Plugin
- [x] Create a new Theme
- [x] Reset Database
- [x] `rake` command
- [x] Nuke the installation
delete everything possible to recreate a known-good state

Those are basic scripts to get you started. We can create more powerful scripts with a better UX later.

**Comment by cngJo** [comment]
We have all the mentioned commands. 
Create separate issues to improve the command, because some of them are very crud and could use some UX improvements.
